### ISSUE TITLE
Config.Frontend.Extensions defaults not working

### ISSUE THREAD

**Issue by mattfysh** [apollographql/apollo-engine-js#102]
According to defaults for frontend extensions (stripping, blacklist), the response should not return any extension/tracing info to the client. (https://www.apollographql.com/docs/engine/proto-doc.html#mdg.engine.config.proto.Config.Frontend.Extensions)

However, using GraphiQL, I am seeing tracing data returned to the client. I've tried explicitly setting the properties (strip and blacklist `tracing`) but this also does not appear to be working. Anything else you'd need me to take a look at before investigating? thanks!

**Comment by zionts** [comment]
Hi @mattfysh,
By default, Engine will set strip to `tracing` and `cacheControl`, so if you're seeing this data returned via GraphiQL, the most likely scenario is that the query isn't going through Engine at all. To figure out why that might be happening, I encourage you to reach out to [support](engine.apollographql.com/support). You can also email support directly via `support@apollographql.com`. If you do determine that the query is going through Engine, but the `strip` / `blacklist` configurations aren't working, definitely reach back out here and we'll investigate and figure out what's going on :)

**Comment by mattfysh** [comment]
only just getting around to following up on this, but the issue I was having was because we serve graphql on a non-standard path (ie. not `/graphql`). Fixed this with the `graphqlPaths` option - thanks!
