### ISSUE TITLE
Help With local HTTPS

### ISSUE THREAD

**Issue by manico** [apollographql/apollo-engine-js#106]
I have a problem with running apollo engine proxy when my node application is running on `https://localhost:8090` (when I run on `http` everything is ok). It seems that proxy is forwarding requests to http no matter what settings for origin and frontend I set.

Is there a working example for this scenario?

**Comment by manico** [comment]
Ok, I found the way. You must use engineConfig.origins.http.url to set full url. This is not possible using origin property, I think because of this:
https://github.com/apollographql/apollo-engine-js/blob/master/src/index.ts#L239

It assigns hard-coded value even if url is set. Assign should be reversed here?

**Comment by zionts** [comment]
Hey @manico, thanks for bringing this up! Just put out a PR to address this
