### ISSUE TITLE
High CPU/memory usage

### ISSUE THREAD

**Issue by elie222** [apollographql/apollo-engine-js#108]
Running a 16 core server with 16 Meteor instances running on it.

Upon server restart the server goes into overload and we see a lot of these processes running:
`engineproxy_lin`

htop showing:
<img width="776" alt="screen shot 2018-01-31 at 17 21 51" src="https://user-images.githubusercontent.com/3090527/35630919-4386e410-06ab-11e8-91ed-7004428e83c5.png">

I think after a while things cool down a bit, but site is unresponsive while this happens. Any ideas?

All 16 cores were at 100% CPU and memory also at full capacity (AWS C4 16 core machine with 32GB RAM)

**Comment by zionts** [comment]
Hey @elie222,
Is htop showing that the engineproxy process is taking up all the cpu / mem or is it shared with the node process? Engineproxy shouldn't be doing anything very resource intensive on startup. To help debug, you can try to use the newly added `debugServer` to profile Engineproxy's performance. Check out the [release notes for 2018.01-43](https://www.apollographql.com/docs/engine/proxy-release-notes.html) for instructions on how to use that.

This also may very well be related to what Meteor is doing on startup, so it's important to understand whether this is actually Engineproxy or the parent node process that is taking up all the CPU / mem. In any event, I recommend that you reach out to Apollo Engine's dedicated [support channel](engine.apollographql.com/support) and file a ticket if you continue to have issues. Hope this helps :)
