### ISSUE TITLE
Plugin should error when not setup as first middleware

### ISSUE THREAD

**Issue by Shahor** [apollographql/apollo-engine-js#117]
Express version: 4.14.0
apollo engine: 0.8.5

When apollo is not the first middleware the graphql queries will just hang and the server won't respond, ever.

This is totally silent and makes it very hard to debug.
Can something be done about this?
I would gladly help, given some hints about where to start maybe.

**Comment by zionts** [comment]
Hey @Shahor thanks for reaching out on this – I think this is basically #62. I really appreciate the offer to help out here, but I'm not sure how it could be done without changes to the proxy binary. This is definitely something we're looking to improve, and if you have any ideas for a quick way to let people know their middleware ordering might be wrong while debugging, I'd love to hear it or see a PR. In the meantime, we've tried to document this heavily in the Engine docs. We could probably port [this troubleshooting guide](https://github.com/apollographql/engine-docs/blob/master/source/troubleshooting.md) here if that might help with visibility, though.

**Comment by zionts** [comment]
Closed so that we could move discussion to #62

**Comment by Shahor** [comment]
Hello @zionts,
thanks for chiming in!

I understand that this might not be an easy fix indeed, hopefully there's a good solution to it but I haven't dwelved into the code enough to be of help right now.

Your documentation states the following:
> Since the Engine middleware needs to process the raw requests to your server before they receive any other modifications, it’s important that this is your app’s **first middleware.**

The phrasing might not be as clear, to a non english native, as one may think. 

> Since the Engine middleware needs to process the raw requests to your server before they receive any other modifications, this **must be your app’s first middleware**.

Might be even clearer. 

That being said, the documentation is great overall and there's not much you can do about it on this topic. 
The thing is that sometimes you'll move some stuff around and it might contain middlewares, that's what happened to me. 
Detecting the origin of the problem was therefore a bit of a pain. 

But hey, I managed and here we are 👍 

Anyways, thank you!
