### ISSUE TITLE
Can't use other extensions

### ISSUE THREAD

**Issue by rportugal** [apollographql/apollo-engine-js#121]
Merging existing extensions (e.g. for logging) with the tracing/cache control ones for Apollo Engine on `formatResponse` doesn't seem to be working, and the following error appears on all queries:
```
Error decoding JSON response from origin
```

The proxy debug logs show the following:
```
{ proxy:
   { error: 'json: cannot unmarshal string into Go value of type map[string]interface {}',
     level: 'warning',
     msg: 'Error reading JSON response from origin.',
     time: '2018-02-08T16:04:33Z' } }
```

**Comment by zionts** [comment]
This bug is currently only restricted to extension keys with non-JSON values (e.g. `extensions: {"foo":"bar"}`. Thanks for bringing it up! I'll look into resolving it right now :)

**Comment by zionts** [comment]
Update @rportugal the fix for this just got merged in – it'll be in the next proxy release. I'll close this out when that happens.

**Comment by rportugal** [comment]
That’s amazing, thanks :)
