### ISSUE TITLE
How to obfuscate data in mutation variables

### ISSUE THREAD

**Issue by thebergamo** [apollographql/apollo-engine-js#125]
Apollo Engine is an amazing product!

One thing, that I realize that could be improved, is a way to obfuscate some sensitive data sent through variables in mutations, as example login/password.

I didn't found it in docs, any insight about how can I do this or how can I help to implement it?

**Comment by thepwagner** [comment]
@thebergamo There are two options:

If you don't want to report ANY variables, you can use the `noTraceVariables` boolean option: https://github.com/apollographql/apollo-engine-js/blob/master/src/index.ts#L113

If you want to hide particular variables by name, you can add them to the `privateVariables` array: https://github.com/apollographql/apollo-engine-js/blob/master/src/index.ts#L115

**Comment by thebergamo** [comment]
Thanks @thepwagner! This is not clear in docs right? Will try to make a PR for that :)
