### ISSUE TITLE
Is there a plan for FreeBSD binary?

### ISSUE THREAD

**Issue by bganicky** [apollographql/apollo-engine-js#126]
Hi, our GraphQL server sits on a FreeBSD machine. At the moment, there's no binary package available for FreeBSD and therefore I get `Error: Unsupported platform` when trying to instantiate `Engine`. Are there any plans to maintain a FreeBSD binary as well? Thanks!

**Comment by thepwagner** [comment]
@bganicky there shouldn't be anything technically preventing this, please 👍 to help us gauge support.

**Comment by thepwagner** [comment]
@bganicky we'd also be interested in any bugs specific to https://www.freebsd.org/doc/handbook/linuxemu.html  , since that allows us to support FreeBSD without any overhead.

**Comment by zionts** [comment]
We encourage users seeking other platforms supported to reach out through our [support channel](engine.apollographql.com/support). Since there is a straightforward workaround for FreeBSD, we do not plan on releasing a FreeBSD binary at this time.
