### ISSUE TITLE
Security issue in hoek 4.2.0 lib

### ISSUE THREAD

**Issue by ralphkocher** [apollographql/apollo-engine-js#129]
apollo-engine 0.8.10 uses the hoek 4.2.0 lib. This version of hoek has an security issue (Prototype pollution attack). Issue is fixed in hoek 5.0.3. Is it possible to update hoek at apollo-engine?

More Info: https://nodesecurity.io/advisories/566

**Comment by zionts** [comment]
Hi @ralphkocher thanks for bringing this up, but I'm confused as apollo-engine only has one non-dev, non-optional dependency (request) and hoek is neither a dev nor an optional dependency. Can you elaborate?

**Comment by zionts** [comment]
Closing as this comment seems to be a duplicate of #85 – Hoek is a transitive dependency through Hapi, but since Hapi is only a dev dependency, it shouldn't affect the security of this `npm` package for users.
