### ISSUE TITLE
Unable to communicate with backend

### ISSUE THREAD

**Issue by MatthieuLemoine** [apollographql/apollo-engine-js#130]
Hi!

Since we added `apollo-engine` to our GraphQL server, we are experiencing the following error : 

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/8517072/36544201-2b625724-17e6-11e8-99dd-19dc013ea26b.png">

It seems to be linked to `apollo-engine` as the error message can be found inside the binaries : 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/8517072/36544384-a6cf421e-17e6-11e8-91e7-09699b09d745.png">

This error seems to occur randomly.

Do you have an idea where it could come from ? Did someone already experienced this issue ?

**Comment by zionts** [comment]
Hi @MatthieuLemoine thanks for reaching out on this! This error indicates that Engine Proxy did not receive a response from the origin GraphQL server. This could mean that the origin specification in the Engine configuration is incorrect, or it could also mean that the request timed out. If you're using a hosting platform, such as Heroku, and you're noticing many of these errors, then you may want to consider changing the requestTimeout of your GraphQL origin. With the current API, this would be done via 
```
new Engine({
  ...
  origin: {
    requestTimeout: "29s"
  }
  ...
});
```
For Heroku users, we recommend a timeout of 29s to accommodate the [outer 30s timeout](https://devcenter.heroku.com/articles/request-timeout#long-polling-and-streaming-responses) from Heroku.

**Comment by tmeasday** [comment]
@zionts which version of engine is the above for? I tried:

```js
const engine = new ApolloEngine({
  apiKey: environment.ENGINE_API_KEY,
  origin: {
    requestTimeout: '29s',
  },
});
```

and I get: 

```
time="2018-03-23T11:38:51+11:00" level=error msg="Error loading configuration." error="parse config from environment variable failed: unknown field \"origin\" in mdg_engine_config_proto.Config"
events.js:183
       throw er; // Unhandled 'error' event
       ^

 Error: Engine crashed due to invalid configuration.
```

**Comment by glasser** [comment]
Hi Tom! That was the pre-1.0 API. Add an s to the end of origin and wrap the object in a pair of [].  We decided that having two very similar but slightly different ways to express the same thing was worse than the convenience of not having to type those three characters.

**Comment by glasser** [comment]
Engine is currently implemented as a proxy that runs in front of your app.  If invalid configuration is provided, it can't run.

If you would like your app to run in a more complex mode where requests sometimes are sent to Engine and sometimes directly to your app, you can build it out of building blocks including the advanced ApolloEngineLauncher API.
