### ISSUE TITLE
Engine dumping traffic, even if dumpTraffic is set to false

### ISSUE THREAD

**Issue by paidit-app** [apollographql/apollo-engine-js#145]
Whether we set the `dumpTraffic` flag to `false`, or just erase it completely, we still see lots of logs being printed to the console. Is there any way to stop them? (any way to silence the engine locally would be greatly appreciated).

It looks something like this:
`{ proxy:
   { level: 'info',
     logLevel: 'debug',
     msg: 'Set log level.',
     time: '2018-02-28T15:27:06+02:00' } }
{ proxy:
   { level: 'debug',
     msg: 'Created origin.',
     name: '',
     time: '2018-02-28T15:27:06+02:00',
     type: 'http',
     url: 'http://127.0.0.1:10000/graphql' } }
{ proxy:
   { host: '127.0.0.1',
     level: 'debug',
     msg: 'Creating frontend service.',
     port: 0,
     time: '2018-02-28T15:27:06+02:00' } }
{ proxy:
   { address: '127.0.0.1:51706',
     level: 'info',
     msg: 'Started HTTP server.',
     time: '2018-02-28T15:27:06+02:00' } }
{ proxy:
   { configured: 0,
     current: 0,
     level: 'debug',
     msg: 'Synchronizing stores.',
     time: '2018-02-28T15:27:06+02:00' } }
{ proxy:
   { level: 'info',
     msg: 'Engine proxy started.',
     time: '2018-02-28T15:27:06+02:00',
     version: '2018.02-37-g678cbb68b' } }`

Additional details:
Our apollo-engine version is 0.8.10 (further versions don't work at all. We guess it is probably expected, since they were not officially released yet)

**Comment by glasser** [comment]
That's not traffic being dumped — it's just normal logs from the proxy.

Strangely it appears that it's showing you the debug log level. Did you specify `{logging: {level: 'debug'}}` in your `new Engine` call?  If not, can you share your `new Engine` call (with secrets redacted)?

Also I'm quite interested in what you mean by "further versions don't work at all".  Oops, I just realized that the test version I published is marked as latest! Grr, wish that wasn't the default with npm for pre-release versions. I've reverted apollo-engine@latest to 0.8.10.  Did you try 0.9.0-test.2, I guess?  What do you mean "don't work at all" — I'd love to know what went wrong so I can avoid it when it's time for the real release very soon!

**Comment by paidit-app** [comment]
Yes we did specify the logging level as `debug`, we just didn't expect the logs to overflow the console (most of our currently downloadable logs on AWS are apollo-engine proxy console logs).

The `new Engine` call is as follows:
`   const engine = new Engine({
        engineConfig: {
            "apiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "logging": {
                "level": "DEBUG"
            }
        },
        graphqlPort: 10000,
        endpoint: '/graphql'
    });`

Even if we specify the logging level as `info`, we still see several logs being outputted, and we would really appreciate an option to turn console logging off.

As for the versioning, we tried both 0.9.0-test.2 and 1.0.0, before switching to 0.8.10. We noticed them, using the `npm show apollo-engine versions` command. Upon usage, the service was crashing instantly and we saw the following error message:
`uncaughtException: Cannot find module 'apollo-engine'`

On a different note, this is a great project, so thank you very much for your contribution. We are definitely looking forward to future releases!

**Comment by glasser** [comment]
Well, debug-level logs are... debug-level logs. There's going to be a bunch of them if you ask for them.

You might want to change the level to something more restrictive rather than less restrictive, eg `level: 'ERROR'`.

To drop all logs, there's currently an undocumented `logger` option, but it'll be replaced by equivalent proxyStdoutStream and proxyStderrStream options in the next release, which you can use with something like https://www.npmjs.com/package/dev-null

1.0.0 looks like a mistake  — it's quite old.  0.9.0-test.2 I would actually expect to work (though not on Windows) and I'm concerned it doesn't...

**Comment by glasser** [comment]
Yeah, 0.9.0-test.2 definitely didn't work on windows - current master (which we hope to release today as 0.9.0) ought to fix that. What exact code were you running when you got that "read only property" crash? That is strange.

**Comment by paidit-app** [comment]
We simply replaced the `"DEBUG"` / `"INFO"` values with `"ERROR"` (`"WARN"` doesn't work either)

**Comment by glasser** [comment]
@paidit-app I think this is due to the complex way we were dealing with log levels, which we fixed last week and just released as 0.9.0. Can you try that and see how it works?

**Comment by paidit-app** [comment]
It works great now, thank you!
