### ISSUE TITLE
Restify support

### ISSUE THREAD

**Issue by johannakate** [apollographql/apollo-engine-js#146]
Restify may not be supported https://github.com/renanlopescoder/node-restify-graphql

**Comment by glasser** [comment]
This should be pretty trivial to support in 1.0.0 (1 line of real code, a few lines of tests).

**Comment by glasser** [comment]
#150 (1.0 API) supports restify

**Comment by zionts** [comment]
https://github.com/apollographql/apollo-engine-js/blob/master/src/engine.ts#L29
