### ISSUE TITLE
Persisted queries don't fully work with CORS

### ISSUE THREAD

**Issue by sbrichardson** [apollographql/apollo-engine-js#152]
I just upgraded from pre-1.0 to version 1.0.1 and started getting a CORS error on the client with my configuration.

I am using the `cors` npm module, a portion of the applicable code is below. This only affects GraphQL requests from the client, non-GraphQL requests are still working properly.

I'm currently checking on this issue, but logging this now since the v1 update is new.

I'm not excluding the fact that this may have been an incorrect CORS configuration, if you have any details I would appreciate it. Thanks

```js
import express from 'express'
import cors from 'cors'
import { ApolloEngine } from 'apollo-engine'
import engineConfig from './engineConfig'

const {
  GQL_SERVER_ENDPOINT,
  PORT = 5000
} = process.env

const engine = new ApolloEngine(engineConfig)

/** Instantiate express app */
const app = express()

/** Add CORS security settings, the whitelist is an array of urls */
const CORSConfig = { origin: CORS_WHITELIST }
  
app.use(cors(CORSConfig))

/** other express code omitted... */

//////////////////
// Start Server //
//////////////////

engine.listen({
  port: PORT,
  graphqlPaths: [GQL_SERVER_ENDPOINT],
  expressApp: app,
}, () => {
  console.info(`App started on :${PORT}`)
})

```

**Comment by glasser** [comment]
Thanks! Can you share with us what exactly the CORS error being logged is?

You aren't using apollo-link-persisted-queries, are you?

**Comment by sbrichardson** [comment]
I was trying out apollo-link-persisted-queries (0.2.0) with a React frontend app. I hadn't taken it very far yet though.

I re-pulled my upgrade to `engine ^1.0.1` and confirmed after removing the persisted query link below the CORS error on the client went away.

This is an example of the chained link built for Apollo client in React. I haven't spent a lot of time on the order or additional link functionality since it's been working.

```js
import { ApolloLink } from 'apollo-link'
import metaLink from './metaLink'
import authLink from './authLink'
import httpLink from './httpLink'
import persistedQueryLink from './persistedQueryLink.js'
import errorLink from './errorLink'

/*****
 * Create chained link
 *****/

const chainedLink = ApolloLink.from([
  metaLink,
  errorLink,
  persistedQueryLink,
  authLink,
  httpLink
])

```

Apologies on going back and forth on this issue and https://github.com/apollographql/apollo-engine-js/issues/155

I figured they may be somewhat related to configuration options availability with the new web proxy.

**Comment by sbrichardson** [comment]
To answer your previous question, here was the error output (generic CORS error):
```
Failed to load [server url] No 'Access-Control-Allow-Origin' header
is present on the requested resource. 
Origin [app url] is therefore not allowed access.
If an opaque response serves your needs, set the request's
mode to 'no-cors' to fetch the resource with
CORS disabled.
```

Should `apollo-link-persisted-queries` not be used any longer on the client?

**Comment by glasser** [comment]
That's what I guessed. We have a high priority bug with the persisted queries implementation in Engine and CORS.

Specifically, in the case where the client sends a hashed query that Engine doesn't yet know about, Engine returns an error to the client telling it to send the full query without ever talking to your GraphQL backend at all. But because it doesn't talk to your backend, it doesn't do its normal role of proxying over your backend's CORS headers.

We have a workaround incoming (hopefully released today) of allowing your to hardcode response headers into your Engine config to be sent with all replies which can be used to fix this for now. Longer term we'd like to have a way to configure the PQ support specifically to include CORS headers, or for the PQ logic to query your GraphQL backend for headers when it would return that particular error.

**Comment by glasser** [comment]
(FWIW I think this is only loosely related to the Engine v1 API. Engine had the same issue before, though I guess if you were careful to put the Engine middleware on your stack after the CORS middleware you could work around it.)

**Comment by glasser** [comment]
I've merged the workaround internally but have not yet had time to roll a release for it. That should come tomorrow, including docs.

**Comment by glasser** [comment]
OK, I released `apollo-engine@1.0.2`. See https://www.apollographql.com/docs/engine/auto-persisted-queries.html for a description of how to use the new overrideGraphqlResponseHeaders option for CORS with APQ.

I'm closing the issue but we are internally tracking improving this experience to require less configuration.

**Comment by glasser** [comment]
This sort of difficulty is why we've reimplemented persisted query support as a core feature of apollo-server in Apollo Server 2.  I'd recommend using that instead.  See https://www.apollographql.com/docs/guides/performance.html#Automatic-Persisted-Queries

**Comment by suciuvlad** [comment]
@glasser I've just upgraded to Apollo Server 2. I'm getting the following error: 


***Failed to load http://[app-url].test:4000/graphql?operationName=OBJECTS_BY_TYPE_QUERY&variables=%7B%22bucketSlug%22%3A%%22%2C%22readKey%2LONG_QUERY_HERE2%3A4%22%7D%7D: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://[app-url].test:3000' is therefore not allowed access.***

Not sure how to change the settings from wildcard to my actual domain.

These are my settings, i haven't overridden persistedQueries config.

```
  const server = new ApolloServer({
    schema,
    tracing: true,
    engine: {
      apiKey: 'service:engineid'
    },
    cacheControl: true
  });
```

and on the client

```
  const link = ApolloLink.from([
    createPersistedQueryLink({ useGETForHashedQueries: true }),
    onErrorLink,
    new HttpLink({
      uri: config.GRAPHQL_SERVER_URL,
      credentials: 'include' // send the headers
    })
  ]);
```

**Comment by glasser** [comment]
I guess it depends how you've set up CORS on your server? You can use the `cors` argument to new ApolloServer. Are you still using apollo-engine too? Apollo Server 2 replaces most of the need to use the separate proxy that's bundled with apollo-engine.

**Comment by suciuvlad** [comment]
@glasser I got it working! Thanks.

I was able to send the required CORS settings via the server middleware. 

```
  server.applyMiddleware({
    app,
    cors: { origin: 'http://[app-url].test:3000' }
  });
```

**Comment by antonbehaeghe** [comment]
@suciuvlad 

This just fixed an issue for me.

What's the difference between
```
app.use(
  cors({
    origin: process.env.FRONTEND_URL,
    credentials: true,
  }),
);
server.applyMiddleware({ app })
```

and 

```
server.applyMiddleware({
  app,
  cors: {
    origin: process.env.FRONTEND_URL,
    credentials: true,
  },
});```

**Comment by suciuvlad** [comment]
@antonbehaeghe It's been a while since i had this issue but if i recall correctly the apollo middleware was actually overriding the app CORS settings.
