### ISSUE TITLE
GraphQL queries stop working when I add the engine middleware.

### ISSUE THREAD

**Issue by clayne11** [apollographql/apollo-engine-js#16]
I have no idea what's going wrong since the proxy appears to be a compiled binary dependency. Is there somewhere I can actually see the code that's running in the proxy?

**Comment by Rowno** [comment]
Same, after adding the middleware I get this error:
```
Error parsing JSON query!
json: cannot unmarshal array into Go value of type graphql.SerializedQuery
```

**Comment by Rowno** [comment]
Looks like it doesn't support [query batching from apollo-client](http://dev.apollodata.com/core/network.html#query-batching). Using the non-batching interface fixes it.

**Comment by clayne11** [comment]
Good catch. I'm using query batching so that must be why.

**Comment by Rowno** [comment]
I just found this in the FAQ:
> This is a known issue. As of version 0.4.11, Engine does not support batched queries. If you would like an update when the fix is released, please contact support@apollodata.com.

https://www.apollographql.com/docs/engine/troubleshooting.html#troubleshooting-faq

**Comment by clayne11** [comment]
Looks like they significantly updated the docs since Sunday when I last looked at them. That FAQ was not there before.

**Comment by turadg** [comment]
Seems this can be closed like https://github.com/apollographql/apollo-engine-js/issues/26
