### ISSUE TITLE
GraphQL Subscriptions with Apollo Engine?

### ISSUE THREAD

**Issue by derek-fong** [apollographql/apollo-engine-js#176]
I am trying to setup Apollo Engine to my App's `express` server with GraphQL subscriptions enabled by following the [Apollo Engine setup guide for express](https://www.apollographql.com/docs/engine/setup-node.html) and [GraphQL subscriptions setup docs](https://www.apollographql.com/docs/graphql-subscriptions/). I came up with something like this: 

```typescript
import express from 'express';
import { ApolloEngine } from 'apollo-engine';
import { execute, subscribe } from 'graphql';
import { SubscriptionServer } from 'subscriptions-transport-ws';

import { schema } from './src/schema';

const app = express();
const port = 3000;

// GraphQL middleware. 
app.use('/graphql', ...);

// Initialize Apollo Engine. 
const engine = new ApolloEngine({
  apiKey: 'API_KEY_HERE'
});

// Start Apollo Engine. 
engine.listen(
  {
    port,
    expressApp: app
  },
  () => {
    // Set up the WebSocket for handling GraphQL subscriptions. 
    new SubscriptionServer({
      execute,
      subscribe,
      schema
    }, {
      server: engine,
      path: '/subscriptions'
    });
  }
);
```

Queries and mutations works fine with the code above. However, I am unable to get subscriptions working - Error message on web browser console: 
`WebSocket connection to 'ws://localhost:3000/subscriptions' failed: Connection closed before receiving a handshake response`. 

Am I missing something?

**Comment by glasser** [comment]
`engine` is not an http.Server, so don't pass it to the SubscriptionServer `server` field.  One way to do this is:

```js
import express from 'express';
import { ApolloEngine } from 'apollo-engine';
import { execute, subscribe } from 'graphql';
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { Server as HttpServer } from 'http';

import { schema } from './src/schema';

const app = express();
const port = 3000;

// GraphQL middleware. 
app.use('/graphql', ...);

const server = new HttpServer(app);

// Initialize Apollo Engine. 
const engine = new ApolloEngine({
  apiKey: 'API_KEY_HERE'
});

// Start Apollo Engine. 
engine.listen(
  {
    port,
    httpServer: server,
  },
  () => {
    // Set up the WebSocket for handling GraphQL subscriptions. 
    new SubscriptionServer({
      execute,
      subscribe,
      schema
    }, {
      server: httpServer,
      path: '/subscriptions'
    });
  }
);
```

Note that this should allow Engine to pass subscriptions through its proxy to your app, but Engine does not currently report statistics and traces from subscriptions.

**Comment by derek-fong** [comment]
Tested and confirmed this is the solution to my problem. Thanks @glasser!

**Comment by grxy** [comment]
@glasser You say that Engine does not yet support subscriptions, but what about queries and mutations sent via WebSocket transport with `apollo-link-ws`?

**Comment by sbrichardson** [comment]
I’m also curious on this, would engine provide any caching benefits as a proxy or just ignore that traffic currently?

More generically, since engine is using the go proxy, should we research things like this there and assume solutions mentioned for the Go proxy lib should work normally? Or is Apollo engine doing a lot or limiting the Go lib in a way we should know? More just asking in context for future research.

**Comment by sbrichardson** [comment]
To clarify I was asking about requests over websocket specifically, not necessarily subscriptions. Thanks

**Comment by glasser** [comment]
The Engine Proxy currently proxies all websockets transparently and doesn't use any of its GraphQL-specific processing on it.

**Comment by glasser** [comment]
Correct — the Engine Proxy only supports analyzing GraphQL over HTTP.

I believe (but am not 100% sure) that upgrading to apollo-server 2 and using apollo-engine-reporting (built in to apollo-server 2) instead of the Engine Proxy will support apollo-link-ws.
