### ISSUE TITLE
Support authenticated memcache services

### ISSUE THREAD

**Issue by joelind** [apollographql/apollo-engine-js#182]
We run our proxies on Heroku and want to use memcache, but the only available options for us use SASL with uersnames/passwords for authentication. Is there a way the engine proxy can use authenticated memcache services?

**Comment by clayne11** [comment]
This seems like a huge oversight. How are we expected to use an external memached instance without auth?

**Comment by sbrichardson** [comment]
For discussion, here is [a link](https://github.com/memcachier/memjs/blob/master/lib/memjs/memjs.js) from another project using SASL (memjs). Though not sure if implementing support would would be need in GO in the closed source, or on the Node/proxy side.

**Comment by krisread** [comment]
This is ridiculous to be omitted, who runs a server with no credentials?

**Comment by sbrichardson** [comment]
I feel like ridiculous is a little harsh, there are many types of environments and ways to connect to data sources (tokens/proxies/private networks/network policies). I'm not super familiar with memcached.

**Comment by tiefenb** [comment]
Please add this feature.

**Comment by glasser** [comment]
We are not currently actively developing the Engine Proxy. Our current suggestion for caching is to use [Apollo Server Data Sources](https://www.apollographql.com/docs/apollo-server/features/data-sources.html) which has an extendible API for cache backend.
