### ISSUE TITLE
Problem Running Apollo Engine on Google App Engine Standard nodejs Environment

### ISSUE THREAD

**Issue by aaronkchsu** [apollographql/apollo-engine-js#190]
Has anyone else run into trouble doing this? My server was working at one point however without upgrading app engine it stopped working in my app engine environment

**Comment by glasser** [comment]
Due to many reports of difficulty running the apollo-engine proxy in interesting environments, we created an alternative: apollo-engine-reporting, part of apollo-server@2. We recommend upgrading to apollo-server 2 and using that instead of the apollo-engine npm package.
