### ISSUE TITLE
Response Caching not caching correctly

### ISSUE THREAD

**Issue by JacobT14** [apollographql/apollo-engine-js#191]
Hello!  I am using Apollo Server v 2.0.0-rc.6 with apollo-engine v 1.1.2.  I have added the engine config to my apollo server and engine is propery recording requests in the engine dashboard.  However, after adding the cache control extension, the cache is not getting hit and I do not know why.  I tried using the default in memory store, and also using a defined in memory store with 100mb cache instead of 50mb, and still no luck.  I have also tried using apollo-server-redis and the same result.  The cache control extension is present on the graphql response.  Any ideas on what I could be doing wrong?

Here is my apollo server

```
const server = new ApolloServer({
  schema: Schema,

  pretty: true,
  graphiql: true,
  tracing: true,
  cacheControl: true,
  engine: {
    apiKey: 'API-KEY-HERE',
    origins: [
      {
        supportsBatch: true,
        requestTimeout: '60s'
      }
    ],
    // Resize the default in-memory cache.
    stores: [
      {
        name: 'inMemEmbeddedCache',
        inMemory: {
          cacheSize: 104857600 // 100 MB; defaults to 50MB.
        }
      }
    ],
    queryCache: {
      publicFullQueryStore: 'inMemEmbeddedCache'
    }
  }
})
```

**Comment by sbrichardson** [comment]
You can set a default cache maxAge (15s-60s for example) when instantiating the graphql server to ensure the cache infrastructure/settings are working. Then all requests will be cached for at least this level. If you don’t have cache annotations in your schema, you will need to add from the client, header or within the resolver by calling the setCache...

Adding a default maxAge helps to catch nested types within a query that you forget to add a cache annotation to. One tip is to set the default maxAge to a weird number, like 33 seconds if you were going to use 30. That way you can easily see which queries you should massage in engine reporting

https://www.apollographql.com/docs/engine/proxy/guides.html#hints-to-schema

**Comment by dohomi** [comment]
@sbrichardson I can report the same issue. I added cacheHints to several queries and they debugged that they are correctly set. Here is my config:
```js
const port = 4000
const graphqlEndpointPath = '/graphql'
// apollo server config
const server = new ApolloServer({
  schema: schemaWithMiddleware,
  context: ({req}) => {
    const user = getUserPermission(req)
    return {
      user: user
    }
  },
  engine: {
    apiKey: process.env.ENGINE_API_KEY
  },
  introspection: true,
  tracing: true,
  cacheControl: {
    defaultMaxAge: 600 // 10 min
  }
})
const app = express()
server.applyMiddleware({app, path: graphqlEndpointPath})
app.listen({port}, async () => {
  console.log(`apollo-server is ready and listens on port ${port}`)
})
```
I made sure all packages are updated. Inside of the engine app I only receive:
```
No cache policy was defined for this operation. 
```
Any idea what could be missing?

**Comment by suciuvlad** [comment]
+1

**Comment by askeet-engine** [comment]
Same error here, I can't make caching work as expected. Neither with schema annotations nor with resolver hints

**Comment by prevostc** [comment]
Same error here, I can't make caching work as expected. Neither with schema annotations nor with resolver hints.
I tried to set every single cache key without success.

```
export const addApiHandler = (srv: express.Application) => {
  const apolloServer = new ApolloServer({
    uploads: {
      maxFileSize: 2000000, // 2Mo
      maxFiles: 1,
    },
    typeDefs,
    resolvers,
    formatError: formatGraphqlError,
    introspection: true,
    cacheControl: {
      defaultMaxAge: 60,
    },
    cache: new InMemoryLRUCache({ maxSize: 50 }),
    tracing: true,
    engine: {
      apiKey: "service:********************",
      debugPrintReports: true,
    },
    context: async ({ req }: { req: express.Request }): Promise<Context> => {
          // init db connection and add to context here
    },
  })
  apolloServer.applyMiddleware({
    app: srv,
    cors: { origin: "*" },
    bodyParserConfig: { type: "json" },
    path: "/graphql",
  })
}
```

**Comment by marconucara** [comment]
Same problem here. 
If I set `engine: false` in ApolloServer options and I switch back to old `const engine = new ApolloEngine({...})` with same options it backs to work fine (even I'm using apollo-server 2).

**Comment by armandorvila** [comment]
Same problem here.

**Comment by boscorat** [comment]
Also experiencing this issue.

**Comment by TimBroddin** [comment]
Same issue here :(

**Comment by shoaibmerchant** [comment]
Facing this issue as well, something going wrong on.

**Comment by glasser** [comment]
Full query caching is only supported in the older "engine proxy" implementation of Engine reporting. We have not yet implemented it natively in Apollo Server. (This is the one feature (other than non-Node server support) that engineproxy supported that is not yet supported in the newer native Engine reporting.) So everything here is working as intended — if you are no longer using the `apollo-engine` npm module, then full request caching is not available.  We are hoping to reimplement this feature soon in apollo-server, at which point we can recommend that all Node users stop using engineproxy.

**Comment by shoaibmerchant** [comment]
@glasser thanks for the quick reply, I am a bit new to this so can you point me or quickly guide on the older engine proxy implementation.

From my understanding this is what I understood -

1. Downgrade ```apollo-server-express``` to 1.x
2. Use ```apollo-engine``` separately

**Comment by marconucara** [comment]
@shoaibmerchant I'm using `apollo-engine` separately without downgrading apollo server. 
It seems fine. You should add it in the upgrade to apollo server 2 guide.

**Comment by glasser** [comment]
These docs explain how to use engineproxy with Apollo Server 2: https://www.apollographql.com/docs/engine/setup-node.html

**Comment by shoaibmerchant** [comment]
Thanks for the help, I did follow the guide. I was able to make it work with 1.x (graphqlExpress) though.

For 2.x, I am doing this - 

```js
const server = new ApolloServer({
			schema,
			tracing: true,
			cacheControl: {
				defaultMaxAge: 180,
			},
			formatError, // error formatting via apollo-errors
			context: ({ req }) => {
				// added additional context
                                 //
				return {
					req: req,
				};
			},
			engine: false,
		});

		server.applyMiddleware({ app });

		const engine = new ApolloEngine({
				apiKey: ENGINE_API_KEY
		});

		console.log('Server (with Engine) started on', this.opts.port);
		engine.listen({
			port: this.opts.port,
			expressApp: app,
		});
```

Doesn't cache the full query, any ideas what is going wrong?

**Comment by dohomi** [comment]
I hope the apollo team member will chip in sometimes soon. As far I found out on the Slack channel the implementation of "Cache-Control" for Apollo Engine is not fully integrated in Apollo v2 - even though the website and docs are stating it. Even everything looks fine on the request and response side, Apollo Engine won't cache the result properly due to some missing implementations.

**Comment by shoaibmerchant** [comment]
Okay that is misleading, thanks for the help

**Comment by TheKidCoder** [comment]
Is there any update here? Having such in-depth docs without having the feature actually implemented is very misleading and honestly a bit shocking.

**Comment by glasser** [comment]
I'm actively working on full query caching for apollo-server this week; see the `glasser/full-query-cache` branch on `apollo-server`.
