### ISSUE TITLE
Hard Dependency On Origin With No Name

### ISSUE THREAD

**Issue by netshade** [apollographql/apollo-engine-js#207]
When initializing the engine with multiple origins, each with its own unique name, if no Origin is provided whose name is the empty string, the configuration is rejected as invalid.

An example configuration:

```
const { ApolloEngineLauncher } = require('apollo-engine');
const launcher = new ApolloEngineLauncher({
  apiKey: 'MYAPIKEY',
  logging: {
    level: 'DEBUG',
  },
  origins: [
    {
      name: 'Origin 1',
      http: {
        url: 'http://localhost:3000/graphql',
      },
    },
    {
      name: 'Origin 2',
      http: {
        url: 'http://localhost:3001/graphql',
      },
    },
  ],
  frontends: [
    {
      port: 3002,
      endpoints: ['/graphql'],
    },
  ],
});
launcher.start().catch((err: Error) => {
  throw err;
});

```

It seems that the desired behavior would be that if no Origin is present whose name is the empty string, then the first Origin in the supplied list of Origins should be selected. Alternatively, the behavior should *always* select the first Origin provided regardless of the value of the `name` field, which would seem to be more consistent behavior across configurations.

**Comment by netshade** [comment]
Error at startup:

```
yarn compile && yarn start
yarn run v1.12.3
$ tsc
✨  Done in 2.00s.
yarn run v1.12.3
$ node ./lib/index.js
ERRO[0000] Error loading configuration.                  error="frontend \"tcp::3002\": origin \"\" not found"
(node:38026) UnhandledPromiseRejectionWarning: Error: Engine crashed due to invalid configuration.
    at ChildProcess.<anonymous> (/Users/shade/opt/src/connectedbits/spot-graphql-gateway/node_modules/apollo-engine/lib/launcher.js:152:41)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
(node:38026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.18s.
```

**Comment by glasser** [comment]
As documented in https://www.apollographql.com/docs/references/proxy-config.html#mdg.engine.config.proto.Config.Frontend the `frontend` object has an originName field, and if left blank, it defaults to the empty-string origin name. So this is working as intended and documented.

I do generally agree that the proxy is too hard to configure. That's part of why it's deprecated and we only suggest it for very specific use cases mentioned at https://www.apollographql.com/docs/references/engine-proxy.html
