### ISSUE TITLE
Frontend Selection Does Not Respect Host Header

### ISSUE THREAD

**Issue by netshade** [apollographql/apollo-engine-js#208]
When issuing an HTTP request whose `Host` header matches a `url` of one of the provided `origin` configurations, that `Origin` is not selected. For example, in the following configuration:

```
const { ApolloEngineLauncher } = require('apollo-engine');

const launcher = new ApolloEngineLauncher({
  apiKey: 'MYAPIKEY',
  logging: {
    level: 'DEBUG',
  },
  origins: [
    {
      http: {
        url: 'http://localhost:3000/graphql',
      },
    },
    {
      name: 'staging-server',
      http: {
        url: 'https://staging.apollographql.com/graphql',
      },
    },
  ],
  frontends: [
    {
      port: 3001,
      endpoints: ['/graphql'],
    },
  ],
});
launcher.start().catch((err: Error) => {
  throw err;
});
```

 When supplying a request whose `Host` header is `staging.apollographql.com`, the `origin` of `localhost` is selected rather than the `origin` of `staging.apollographql.com`.  

While there are configuration options to produce the desired origin selection behavior in the backend, it seems like specifying the `Host` would also work and be a natural way for backend selection to occur. 

/label feature

**Comment by glasser** [comment]
The engine proxy is currently deprecated and we do not have any plans to add additional convenience features to it at this time.
