### ISSUE TITLE
error peeking at request

### ISSUE THREAD

**Issue by maksymseleznov** [apollographql/apollo-engine-js#209]
Hi everyone,

Can you help me to find out what this error means `error peeking at request: unexpected EOF` and how I can to debug it?
```
"time="2018-12-21T18:22:04Z" level=warning msg="Query error" code=400 error="error peeking at request: unexpected EOF" message="The query failed."
```

```
    "apollo-engine": "1.1.2",
    "apollo-server-express": "2.3.1",
```

**Comment by glasser** [comment]
The engine proxy is deprecated and we only suggest it for the specific use cases mentioned at https://www.apollographql.com/docs/references/engine-proxy.html

Are you using one of those specific use cases? The new native JS metrics instrumentation is built in to apollo-server 2 which you are using.

**Comment by maksymseleznov** [comment]
thanks
