### ISSUE TITLE
how can i use privateVariables with apollo-engine?

### ISSUE THREAD

**Issue by maksymseleznov** [apollographql/apollo-engine-js#210]
I have sensitive information in the payload response. how can I use privateVariables with apollo-engine?

**Comment by glasser** [comment]
(Note: The engine proxy is deprecated and we only suggest it for the specific use cases mentioned at https://www.apollographql.com/docs/references/engine-proxy.html)

By the "payload response", you mean the response from your GraphQL server to the client?  We never send any contents from the response to our servers other than errors.

**Comment by maksymseleznov** [comment]
thank you
