### ISSUE TITLE
Apollo Engine not working when deployed on Zeit Now

### ISSUE THREAD

**Issue by hakimelek** [apollographql/apollo-engine-js#212]
I am running [graphql-yoga](https://github.com/prisma/graphql-yoga) and adding the apollo-engine config. As in #156, locally I am able to see the requests in engine but when deployed using Zeit Now, it is not working. Applying the `overrideRequestHeaders` did not work and I suspect because it is not supported anymore in the new version of apollo-engine. Also, running the server in Docker is not possible anymore starting in Now 2.0. Any pointers about a workaround here?

**Comment by glasser** [comment]
The apollo-engine package is deprecated and is not being actively developed. We recommend that all users of Node GraphQL servers should use Apollo Server 2's built in Engine reporting support instead.

**Comment by hakimelek** [comment]
@glasser Added deprecation message in Readme #214.
