### ISSUE TITLE
graphqlPaths option, ineffective

### ISSUE THREAD

**Issue by youfoundron** [apollographql/apollo-engine-js#213]
When creating and engine instance with the `graphqlPaths` option, paths other than `'/'` do not work.

**Comment by glasser** [comment]
The apollo-engine package is deprecated and is not being actively developed. We recommend that all users of Node GraphQL servers should use Apollo Server 2's built in Engine reporting support instead. We are working on improving the situation for non-Node users.

**Comment by youfoundron** [comment]
I specifically endeavor to use Apollo Engine w/ Prima's `graphql-yoga`.
Having to use ApolloServer makes paying for Engine a non-starter now :(

Something to consider!

**Comment by glasser** [comment]
@youfoundron `graphql-yoga` is a [convenience layer on top of `apollo-server`](https://github.com/prisma/graphql-yoga/blob/33987a018e575095bebd33e65b4853d0f0ea413c/package.json#L42-L43).

They still are using Apollo Server 1, but it looks like [their new work on "yoga 2"](https://github.com/prisma/yoga2/blob/8516b925435b5e75b869424767f559ab893b4d9c/packages/yoga/package.json#L17) is going to upgrade to Apollo Server 2.
