### ISSUE TITLE
No status report detected in GitHub

### ISSUE THREAD

**Issue by mthomas87** [apollographql/apollo-engine-js#215]
We tried to integrate Apollo Engine Schema validation into our CI-Pipeline (Jenkins) in order to check the results in GitHub.

But unfortunately the GitHub-Plugin can't recognize any reports. 
It's just saying "**Expected - Waiting for status to be reported**"

![bildschirmfoto 2019-02-15 um 15 21 59](https://user-images.githubusercontent.com/6641079/52862440-97201280-3135-11e9-9681-01c7c64f760a.png)

The checks are reported in our build pipeline like this:

```
npm install apollo
./node_modules/.bin/apollo service:check '--key=service:company+key' '--endpoint=our-application/api/graphql'
```

The result seems to be reported correctly:

```
./node_modules/.bin/apollo service:check '--key=service:company+key' '--endpoint=our-application/api/graphql'
[12:47:32] Loading Apollo Project [started]
[12:47:32] Loading Apollo Project [completed]
[12:47:32] Checking service for changes [started]
[12:47:33] Checking service for changes [completed]


Change   Code                        Description
───────  ──────────────────────────  ───────────────────────────────────────────────────────────────────────────────────────────────────────
WARNING  ARG_DEFAULT_VALUE_CHANGE    `Query.something` arg `input` has changed defaultValue
NOTICE   ARG_REMOVED                 `Query.someOther` arg `url` was removed
NOTICE   FIELD_ADDED                 `someOther.redirect` was added
NOTICE   TYPE_ADDED                  `someOther` added`
```

On the "Checks" Tab also no reports.

![bildschirmfoto 2019-02-15 um 15 29 49](https://user-images.githubusercontent.com/6641079/52862911-b0758e80-3136-11e9-8c67-1b01196db952.png)

Did we forget to setup something in Apollo Engine or GitHub? Or do you have any experiences for Jenkins integration?
Thanks for your help!

**Comment by glasser** [comment]
Hi — this is the Git repo for a deprecated module for sending data to Engine, and its issue tracker isn't monitored super closely. If you use the support link (chat bubble) in the bottom right of the Engine UI you'll get straight to the Engine product team.  I'll send this to them too but it'll be easier to track if you start a conversation in the support interface!
