### ISSUE TITLE
Requires process.env.PORT to be set to a number when it may not be possible (iisnode)

### ISSUE THREAD

**Issue by ngbrown** [apollographql/apollo-engine-js#28]
I tried adding `apollo-engine` to an existing apollo graphql express.js application.

I was getting the following error in development:

```
[nodemon] restarting due to changes...
[nodemon] starting `babel-node ./bin/www`
D:\dev\gateway\node_modules\apollo-engine\lib\index.js:27
                throw new Error('process.env.PORT is not set!');
                ^

Error: process.env.PORT is not set!
    at new Engine (D:\dev\gateway\node_modules\apollo-engine\src\index.ts:105:23)
    at Object.<anonymous> (D:/gateway/src/apolloEngine.js:3:16)
    at Module._compile (module.js:570:32)
    at loader (D:\dev\gateway\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\gateway\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
[nodemon] app crashed - waiting for file changes before starting...
```

**Edit:** I figured the port thing out.  It was happening because `require('./app')` (where apollo-engine is created) is happening before the port environment variable is read and set to the Express.js `port` variable.  At this point, I tried setting the default back to the environment variable, but it was too late.  There is still an issue with how to run this on iisnode with no port number at localhost to connect back to.

When not in development mode like above, this application actually runs on [iisnode](https://github.com/Azure/iisnode), which means that `process.env.PORT` is actually set to a Windows pipe name.  It appears that `apollo-engine` needs to make a request back into the express.js application after it handles the request.  Is there any other way than going through HTTP?

Maybe a direct connection to the `graphql-server-express` instead?

**Comment by zionts** [comment]
Hi @ngbrown, thanks for bringing this to us here and digging a little deeper into it to figure out what was going on. As a starting point, I've updated the error message for that use case to include more helpful information. 
Unfortunately, right now it's essential to have a port number to connect back to, but if this is a blocker for you, you can also run Engine Proxy via a stand-alone Docker Container (https://www.apollographql.com/docs/engine/setup-node.html#standalone-docker-container). Right now the middleware is doing a double-proxy, so it's necessary that apollo-engine make a request back to the application. It's possible to do a single-proxy as well, and we are working on building out better support and guidance for that use case. Supporting other protocols beyond HTTP is on the roadmap, so I'll mark this issue as `roadmap` for that reason.
In the meantime, to get quicker, dedicated support for Apollo Engine, please reach out directly to support via email (support@apollographql.com) or by submitting a ticket directly from the Engine UI (https://engine.apollographql.com/support). If you're still having trouble with the same issue, I'd recommend looking to set up Engine via a Docker container as I mentioned above or to dig a little deeper into the middleware supplied here to see if you can massage it to work for you use case.

**Comment by zionts** [comment]
Please 👍 if this is an issue you'd like addressed

**Comment by JeffJankowski** [comment]
I would like to see this issue addressed as well. I am currently hosting apollo-server inside an Azure Web App. Since Azure runs iisnode under-the-hood, there is no port number to reference when loading Engine's sidecar package, only a named pipe.

The pricing structure of Azure Container Instances is relatively cost-prohibitive to continuously-running workloads, so Docker is not an idea alternative for me.

**Comment by zionts** [comment]
In order to better collect feature requests and bug reports that relate to Apollo Engine Proxy, we have moved this issue (Support for Named Pipes) into our internal issue tracker, and correspondingly closing this issue. This is in an effort to collect all customer feedback into the most appropriate place so we can better iterate on the features you want most. For any future feature requests, issues, or questions about the Apollo Engine Proxy binary, we urge you to [reach out directly to our team](https://engine.apollographql.com/login?overlay=SupportRequestNoAccount). We appreciate your help in improving Apollo Engine!

**Comment by ngbrown** [comment]
iisnode makes running node applications on Windows fairly straightforward and is nicer in production than creating services running PM2.  IIS provides limited user accounts as well as deployment options in a fairly standard way compared to custom services.

The named pipe from iisnode looks like this: `\\.\pipe\c31c522f-c240-4588-acb1-f14c5962168c`.  There is a Go package to integrate with named pipes, so that should help.  <https://github.com/natefinch/npipe>.

Is there any way to monitor the progress of internal issues?

**Comment by mlabrum** [comment]
Hey, 

Has there been an update to this issue? We're trying to run a nodejs app on Azure app services and hitting issues with iisnode and named pipes

Thanks,

**Comment by ngbrown** [comment]
It seems to only partially be working.  The `pipePath` is accepting the pipe name string, and it is proxying the request to the express server port, and adding a custom header, and returning the response to the client.

However, it's not reading the response extensions value, sending them to the engine website, or stripping the extensions from the response.  It did connect to the website with the API key and finish "setup", but no queries have shown up.

This appears to be an issue with the Go binary, so I can't look at what is going on.  The engine was working locally with all port numbers on the current release.

**Comment by zionts** [comment]
@ngbrown what does your call to engine.listen(...) look like and what do the DEBUG logs output from engineproxy say? The behavior you're mentioning indicates to me that engineproxy is proxying the request as non-graphql. You can verify that by setting `overrideGraphqlResponseHeaders`.

**Comment by ngbrown** [comment]
> The behavior you're mentioning indicates to me that engineproxy is proxying the request as non-graphql and not interpreting the response.

Yep, that's exactly what it was.  I forgot I had to change the `graphqlPaths` for the QA server because it's in a virtual directory different than my local computer.  It's working great.

On the whole port/pipePath thing, it since Express can take both as a single parameter, it would be awesome if the engine would automatically figure out that the passed `port` value is a string or a number.

I already had a `normalizePort` function in my Express startup file:

```js
const port = normalizePort(process.env.PORT || '3002');
...
const server = http.createServer(app);
if (process.env.NODE_ENV !== 'test') {
  const engine = apolloEngineFactory();
  engine.listen({
    port: typeof(port) === 'string' ? undefined : port,
    pipePath: typeof(port) === 'string' ? port : undefined,
    httpServer: server,
  });
} else {
  server.listen(port);
}

function normalizePort(val) {
  const port = parseInt(val, 10);
  if (isNaN(port))  return val;
  if (port >= 0)  return port;
  return false;
}
```

The above `server.listen(port);` worked on both port number and pipe strings, so instead of the conditional operators, just sending a normalized port/pipe to a `port` option would be ideal.  This is something that the Engine JS interface could sort out and set the correct option for the Go binary.

**Comment by zionts** [comment]
@ngbrown thanks for the suggestion! I added the functionality into master (https://github.com/apollographql/apollo-engine-js/pull/183) and it will be available in the next release.
