### ISSUE TITLE
GraphQL proxy server strips out custom fields in GraphQLError object 

### ISSUE THREAD

**Issue by emmenko** [apollographql/apollo-engine-js#30]
Hey guys,

I need to pass some custom fields on a GraphQLError object, specific to my API.
As far as I know the spec allows to do that.

> GraphQL servers may provide additional entries to error as they choose to produce more helpful or machine‐readable errors, however future versions of the spec may describe additional entries to errors.

http://facebook.github.io/graphql/October2016/#sec-Errors

For the sake of understanding the problem I have, in the `formatError` function I pass an extra field (besides `message`, `locations`, `path`):

```js
formatError: graphqlError => ({
  message: graphqlError.message,
  locations: graphqlError.locations,
  path: graphqlError.path,
  foo: 'bar',
}),
```

#### Without Apollo Engine (middleware disabled)
When I don't have Apollo Engine running, more specifically the middleware is not used, I get in the frontend the response with the error object containing the custom field.

#### With Apollo Engine (middleware enabled)
When I have Apollo Engine running though, the response error object does not contain the custom field I provided, even though the ["express apollo server" writes the response](https://github.com/apollographql/apollo-server/blob/671d196c77356efd212e2f17a22353aacbf1e9a5/packages/apollo-server-express/src/expressApollo.ts#L37) with the object containing the custom field.

I'm wondering then **if Apollo Engine somehow strips out** those "fields" that _it does not recognise_ even though the spec should allow that.

Can someone please clarify this? Thanks a lot 🙏

**Comment by thepwagner** [comment]
Just acknowledging: this is a bug in the proxy binary that will be fixed soon.

**Comment by emmenko** [comment]
Thanks for the info!

**Comment by ricklancee** [comment]
Has this been fixed?

**Comment by emmenko** [comment]
Would be good to know yes: https://github.com/apollographql/apollo-engine-js/pull/40#issuecomment-344210138

**Comment by thepwagner** [comment]
Fixed, but not released yet.

Proxy updates will create a PR like https://github.com/apollographql/apollo-engine-js/pull/34 ; that's where we'll flag issues as fixed, and provide a cross-reference to proxy binary version in the release notes.
