### ISSUE TITLE
GET requests to Graphql endpoint causes memory leak when Apollo Engine is enabled

### ISSUE THREAD

**Issue by thisisamurray** [apollographql/apollo-engine-js#45]
Hey All,

When we enable Apollo Engine on our Express server, whenever someone hits our graphql endpoint with a GET request, instead of a POST, something within Apollo Engine causes the server to crash after a few seconds due to it running out of available memory.

Attempted to have Express intercept GET requests to return an error before it executes any Apollo middleware, and it will still have the problem. Tried to trace the error, and it looks like a function hits `net.js` within node repeatedly until there are no resources left on the device.

Once Apollo Engine is disabled, or not included as middleware, it behaves normally.

Any ideas on how to fix or prevent this issue?

**ENV:**
```
"apollo-engine": "^0.5.0",
"apollo-server-express": "^1.2.0",
"graphql": "^0.10.0",
"express": "^4.16.2",
"cors": "^2.8.1",
```

**IMPLEMENTATION:**
```
import express from "express";
import http from "http";
import path from "path";

import { Engine } from "apollo-engine";

import bodyParser from "body-parser";
import { makeExecutableSchema } from "graphql-tools";
import { graphqlExpress } from "apollo-server-express";
import cors from "cors";

import GraphQLResolver from "./resolver.js";
import Resolvers from "./data/resolvers";
import Types from "./data/types";
import Schemas from "./data/schema";

const app = express();
app.use(cors());

const ApolloEngine = new Engine({
   engineConfig: {
     apiKey: process.env.APOLLO_ENGINE_API_KEY
   },
   graphqlPort: process.env.PORT || 14000,
   endpoint: "/v1",
});

ApolloEngine.start();
app.use(ApolloEngine.expressMiddleware());

app.use( "/v1", bodyParser.json({limit: "10mb"}), graphqlExpress((req) => {
    let appSchema = makeExecutableSchema({
      typeDefs: GraphQLResolver.generateSchema(),
      resolvers: GraphQLResolver.generateResolvers(),
      allowUndefinedInResolve: false,
      printErrors: true,
    });

    return {
      schema: appSchema,
      context: req.context,
      tracing: !!process.env.APOLLO_ENGINE_API_KEY,
      cacheControl: !!process.env.APOLLO_ENGINE_API_KEY,
      rootValue: {
        schema: appSchema,
        resolver: GraphQLResolver,
        endpointHook: AuthenticationHelper.ModifyContext,
      }
    };
  }));

  const PORT = process.env.PORT;

  const Server = http.createServer(app, (req, res) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE,OPTIONS");
    res.header("Access-Control-Allow-Headers", "Content-Type, Authorization, Content-Length, X-Requested-With");
    res.writeHead(404);
    res.end();
  });

  Server.listen(PORT);
```

**Comment by thepwagner** [comment]
Can you try upgrading to `apollo-engine->=0.5.3`?

This sounds like an issued fixed in https://github.com/apollographql/apollo-engine-js/pull/34  - a GET request without a `?query=` parameter would be routed by the middleware to the proxy binary, who would incorrectly route it back to the middleware in such a way to trigger an infinite request loop (i.e. the middleware would route back to the proxy, which would route back to the middleware, ...)

**Comment by thisisamurray** [comment]
Yes, upgrading to 0.5.3 has it working perfectly. Thanks!
