### ISSUE TITLE
Engine breaks queries with array of enums as variable

### ISSUE THREAD

**Issue by clayne11** [apollographql/apollo-engine-js#53]
When I run a query with an array of enums through `apollo-engine` it concatenates all the enums into one string and breaks the query.

```graphql
query {
  myQuery(
    states: [NEW, OLD]
  ) {
    id
  } 
}
```

I get an error saying `invalid enum value NEWOLD`.

**Comment by clayne11** [comment]
I'm still having this issue with the newest version of `apollo-engine`.

**Comment by thepwagner** [comment]
@clayne11 can you run
```eval "$(find node_modules -name engineproxy_darwin_amd64) -version"``` 

I can't reproduce the error with your specific query, so I'd like to be 100% that you're running the latest proxy version.

**Comment by clayne11** [comment]
Looks like it's actually this issue (https://github.com/apollographql/apollo-engine-js/issues/66) and I'm not getting the right version.
