### ISSUE TITLE
Problems with Gzip + Koa + Apollo Engine 

### ISSUE THREAD

**Issue by skevy** [apollographql/apollo-engine-js#54]
At Expo, our Android client sends `application/json; charset=utf-8` as the Content-Type header for our GraphQL requests. After enabling Apollo Engine, we noticed that the requests started failing on Android (but not on other clients that didn't send that same header).

Upon CURL-ing with:

```
> curl --compressed -i -X POST -H "Accept-Encoding: gzip" -H "Content-Type: application/json; charset=utf-8" -d '{"query":"..."}' http://localhost:3000/--/graphql
```

I was able to replicate the issue:

"curl: (23) Error while processing content unencoding: invalid block type"

When Apollo Engine is not in the mix, this request works correctly.

Our Koa server is complex, but the simplified repro case is:

```
....
const app = new Koa();
app.use(compress());
app.use(engine.koaMiddleware());
app.post('/graphql', ...graphql Koa middleware...);
...
```

Here's my guess as to what's happening, without being able to see the source for the Apollo Engine binary:

Request _without_ `charset=utf-8` in the `Content-Type` header:

1. Request is piped to the Apollo Engine binary
2. Inside Engine binary, it queries the upstream with the same request headers
3. A gzipped response is returned from the upstream and decoded + parsed correctly by the Engine binary
4. The `Content-Encoding: gzip` header is stripped, and a raw json response body is returned back to Koa when the request completes
5. The Koa middleware chain continues, and the JSON output from the Engine binary is re-gzipped correctly.

Request _with_ `charset=utf-8` in the `Content-Type` header:

1. Request is piped to the Apollo Engine binary
2. Inside Engine binary, it queries the upstream with the same request headers
3. Something inside the Engine binary decides to do something different with the gzipped response from the upstream due to the `charset=utf-8`, and fails to parse the response.
4. The Engine binary passes the response back as-is to Koa, because it didn't know what to do with it. At the same time, it somehow corrupted the response (maybe because of some weird unicode issue when passing the data back and forth across stdout/stdin?)
5. The response from the Engine binary is _not_ re-encoded by the koa-compress middleware, because the `Content-Encoding` header is set in the response, and the corrupted response is returned.

Note -- steps 4 and 5 there are iffy to me (and I very well might be wrong), simply because I don't have access to the source. I just hope that my rundown here can help you all pinpoint the problem.

Let me know how else I might be able to help with this issue.

The workaround of disabling compression for the GraphQL endpoint works for now, but this behavior seems worth fixing. It's unexpected behavior that was tough to fully root cause.

**Comment by zionts** [comment]
This has been fixed in the newest binary release of the proxy. If you're having similar issues, as a first step, please update apollo-engine-js to the newest version and ensure that the engineproxy binary has been updated as well. To see full release notes, please check here: https://www.apollographql.com/docs/engine/proxy-release-notes.html.
