### ISSUE TITLE
Engine should not swallow caching information

### ISSUE THREAD

**Issue by kbrandwijk** [apollographql/apollo-engine-js#56]
The documentation for Apollo Cache Control states that caching hints from the server may be used (either now or in the future, I haven't investigated) to invalidate client side cache.

However, when using Apollo Engine, the tracing and caching information is only sent to Engine, and excluded from the query response.

It should be possible to preserve the caching information and include it in the response to the client, even when using Apollo Engine.

**Comment by thepwagner** [comment]
@kbrandwijk sorry about this; we changed the default behaviour in the `2017.11-40-g9585bfc6` release of the proxy binary, https://www.apollographql.com/docs/engine/proxy-release-notes.html . We haven't exposed+documented this through the `apollo-engine-js` documentation/config yet - we didn't think anybody was using the extensions downstream yet, it's awesome that you are!

There's a PR open to expose the configuration required to have the proxy passthrough `cacheControl` extensions.

**Comment by kbrandwijk** [comment]
@thepwagner Thank you for the explanation. So if I understand correctly, the engine configuration will soon expose a setting to passtrough the extension info? And the PR you linked to is the one to watch for that?

**Comment by thepwagner** [comment]
@kbrandwijk  Correct; as of `apollo-engine-0.6.0`, a config like:
```
new Engine({
  engineConfig: { ... },
  frontend: {
    extensions: {
      strip: ["tracing"],
    }
  }
})
```

Will result in cache headers being returned by the proxy.
