### ISSUE TITLE
Allow ability to disable https cert checks for development purpose

### ISSUE THREAD

**Issue by aaronCammy** [apollographql/apollo-engine-js#59]
We use self signed certs on local development machines for https. This causes problems with the apollo engine proxys which does not allow non CA signed certs and error out when posting to the graphql endpoint. Having a flag to switch off this check only for dev would be helpful

**Comment by thepwagner** [comment]
This has been added to the `0.8.3` release.

To disable HTTPS checks:
```javascript
const engine = new Engine({
  origin: {
    http: {
      disableCertificateCheck: true
    }
  }
});
```

Alternatively (and more securely) you can configure a path to a custom CA, which must be encoded in PEM form:
```javascript
const engine = new Engine({
  origin: {
    http: {
      trustedCertificates: '/home/pwagner/my-ca.pem'
    }
  }
});
```
