### ISSUE TITLE
charset=utf-8 breaks reporting

### ISSUE THREAD

**Issue by haydentherapper** [apollographql/apollo-engine-js#60]
We found that when the Content-Type header include `charset=utf-8`, the tracing data is not stripped out from the query and the query is not sent to the Engine reporting service. We tested the following two scenarios:
* Header was `Content-Type:application/json;charset=utf-8` - Queries with this header were not reported and extension tracing data was passed back to the client.
* Header was `Content-Type:application/json` - Queries with this header were reported and tracing data was properly stripped.

This issue is related to https://github.com/apollographql/apollo-engine-js/issues/54. However, we did not include `Accept-Encoding: gzip` when testing.

**Comment by thepwagner** [comment]
@haydentherapper thanks for the report - this will be fixed in the next binary release of the proxy.

**Comment by thepwagner** [comment]
This is fixed in https://www.apollographql.com/docs/engine/proxy-release-notes.html#2017-11-121-g2a0310e1b-2017-11-30

Released in `apollo-engine-0.6.0`.
