### ISSUE TITLE
Improve behaviour when the proxy has crashed

### ISSUE THREAD

**Issue by thepwagner** [apollographql/apollo-engine-js#61]
As an apollo-engine-js user,
I want my application to return 503 responses while the proxy binary is not running,
So that no requests are processed without being tracked by engine.

As an apollo-engine-js user,
I want an invalid engine configuration to break my app permanently,
So that if I've installed middleware and called `.start()`, engine is either working or my GraphQL endpoint is down.

**Comment by zionts** [comment]
@thepwagner is this one good to be closed out?

**Comment by thepwagner** [comment]
@zionts nope - https://github.com/apollographql/apollo-engine-js/blob/master/src/index.ts#L309 we still cause the middleware to not route when the proxy binary crashes.

**Comment by glasser** [comment]
This is not relevant with the 1.0 API because there is no double proxying.
