### ISSUE TITLE
middleware health check

### ISSUE THREAD

**Issue by thepwagner** [apollographql/apollo-engine-js#62]
As an engine-proxy developer,
I want apollo-engine-js to return a `200 OK` to some specially crafted request to the GraphQL endpoint,
So that I can verify middleware routing during startup.

Something like `X-Engine-From: $headerSecret ; X-Engine-Health-Check: true` ?
Then on startup the proxy can detect `HeaderSecret` and fire a test request to verify middleware ordering is acceptable.

**Comment by zionts** [comment]
See #117 for more discusson

**Comment by thepwagner** [comment]
Could we just use `{ __typename }`?

**Comment by zionts** [comment]
There will be no middleware in the new API, so closing this out
