### ISSUE TITLE
apollo-engine-binary is huge

### ISSUE THREAD

**Issue by huangbong** [apollographql/apollo-engine-js#64]
```
3.1M	express-jwt
3.1M	moment
3.2M	node-pre-gyp
4.8M	lodash
5.1M	fbjs
5.4M	eslint
7.2M	core-js
9.3M	fsevents
 22M	apollo-engine-binary-darwin
 22M	apollo-engine-binary-linux
 22M	apollo-engine-binary-windows
 29M	aws-sdk
```
The binaries take up 66mb of space in `node_modules`. AWS Lambda code limit is 50mb so you can't use serverless with apollo-engine... Any way to fix this?

**Comment by thepwagner** [comment]
The binaries are optional dependencies, https://github.com/apollographql/apollo-engine-js/blob/master/package.json#L28 , so you can trim down by only installing the version required by the target platform.

That said, Engine uses a persistent proxy process that will NOT behave well within a Lambda environment.
For running GraphQL in Lambda, we suggest running engine as a Docker container, which will in turn invoke your Lambda functions and return their responses - https://www.apollographql.com/docs/engine/setup-lambda.html .
This will keep the Engine Proxy process running persistently for stats aggregation, by running it outside of Lambda.
