### ISSUE TITLE
Error loading configuration

### ISSUE THREAD

**Issue by juliocanares** [apollographql/apollo-engine-js#66]
Hi guys, I am getting this error while trying to setup Apollo Engine.

```
Engine crashed unexpectedly with code: 1
time="2017-12-03T21:58:06-05:00" level=error msg="Error loading configuration" error="parse config from stdin failed: unknown field \"destination\" in mdg_engine_config_proto.Config_Logging"

Engine crashed unexpectedly with code: 1
(node:66456) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: timed out
(node:66456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**this is my configuration**

```js
const engine = new Engine({
  apiKey: process.env.APOLLO_ENGINE_API_KEY,
});
engine.start();

const app = express();
app.use(engine.expressMiddleware());

app.use(
  '/graphql',
  cors(),
  graphqlExpress({
    schema,
    tracing: true,
    cacheControl: true,
  }),
);
```

**versions**

```js
{
    "apollo-engine": "^0.6.0",
    "apollo-server-express": "^1.2.0"
}
```

any thoughts?

**Comment by thepwagner** [comment]
@juliocanares are you upgrading from an earlier version of `apollo-engine`?

That error message seems like the apollo-engine binary in `node_modules/apollo-engine-binary-${platform}` isn't the correct version ; you can verify with:
```
$ node_modules/apollo-engine-binary-darwin/engineproxy_darwin_amd64 -version
engine-proxy 2017.11-121-g2a0310e1b
```

**Comment by dlredden** [comment]
I'm having the same issue after an upgrade. I ran the command you requested and this was the response.

engine-proxy 2017.11-84-gb299b9188

**Comment by juliocanares** [comment]
@thepwagner I was using `apollo-optics`, I ran the command and got this.

```
engine-proxy 2017.11-84-gb299b9188
zsh: command not found: engine-proxy
```

**Comment by zionts** [comment]
As @thepwagner mentioned, this may be an issue with using an older version of apollo-engine. The current version we recommend using is `engine-proxy 2017.11-121-g2a0310e1b`. 

As a first step, try to upgrade to that version using `rm -rf node_modules && npm install`. You can verify that this upgraded engine-proxy to version `2017.11-121-...` by running the version command again (`node_modules/apollo-engine-binary-darwin/engineproxy_darwin_amd64 -version`) and now that should print out `engine-proxy 2017.11-121-g2a0310e1b`.

To see a list of release notes for different versions of Engine Proxy, you can check out https://www.apollographql.com/docs/engine/proxy-release-notes.html.

If the upgrade doesn't resolve your issue, please write back here and I'll be happy to further troubleshoot or you can email support at support@apollographql.com :)

**Comment by dlredden** [comment]
I tried your suggested fix and was surprised to see 2017.11-84-... still being returned as the version. This was after a completely fresh install. So, I dug around and found this in my yarn.lock file.

```
apollo-engine-binary-darwin@^0.2017.11-121-g2a0310e1b:
  version "0.2017.11-84-gb299b9188"
  resolved "https://registry.yarnpkg.com/apollo-engine-binary-darwin/-/apollo-engine-binary-darwin-0.2017.11-84-gb299b9188.tgz#1e863513bb4dce66edd7fe9f12014d55a1c9bed6"

apollo-engine-binary-linux@^0.2017.11-121-g2a0310e1b:
  version "0.2017.11-84-gb299b9188"
  resolved "https://registry.yarnpkg.com/apollo-engine-binary-linux/-/apollo-engine-binary-linux-0.2017.11-84-gb299b9188.tgz#02c4e96b1689fd9d1302535d57de8e60bc763688"

apollo-engine-binary-windows@^0.2017.11-121-g2a0310e1b:
  version "0.2017.11-84-gb299b9188"
  resolved "https://registry.yarnpkg.com/apollo-engine-binary-windows/-/apollo-engine-binary-windows-0.2017.11-84-gb299b9188.tgz#706bda576e004c0763a95fd1570f7c7a9718a5df"

apollo-engine@0.6.0:
  version "0.6.0"
  resolved "https://registry.yarnpkg.com/apollo-engine/-/apollo-engine-0.6.0.tgz#ed3d52f14dec60b7e4551d21d764a6081d58b344"
  dependencies:
    request "^2.81.0"
    stream-json "^0.5.2"
  optionalDependencies:
    apollo-engine-binary-darwin "^0.2017.11-121-g2a0310e1b"
    apollo-engine-binary-linux "^0.2017.11-121-g2a0310e1b"
    apollo-engine-binary-windows "^0.2017.11-121-g2a0310e1b"
```
It seems like yarn has pinned those packages to the wrong version. I'm not sure why this is the case, where this pinned version came from and why it wasn't corrected when the apollo-engine package was updated.

**Comment by jamesone** [comment]
I also get this issue. I'm using v0.6.0 with node v8.6 (i also tried node v6.2)

**Comment by zionts** [comment]
@dlredden Thanks for digging a little more into this. It looks like you're right and there's a good chance that the yarn.lock file is causing issues. We've removed the yarn.lock file from the repo to hopefully avoid this confusion in the future. 

I did fresh yarn clean and upgrade after the clean npm install and it successfully upgraded the binaries.  Try `rm yarn.lock && yarn install && yarn upgrade apollo-engine@0.6.0` and hopefully that will be the proper upgrade. Let me know if it resolves the issue!

**Comment by juliocanares** [comment]
@dlredden I've tried the workaround without success, still getting the same error

**Comment by dlredden** [comment]
@zionts That did it for me. Thanks

**Comment by Darkbladecr** [comment]
Resolved the problem by upgrading the engine-proxy directly:
`yarn upgrade apollo-engine-binary-darwin apollo-engine-binary-linux apollo-engine-binary-windows`

**Comment by zionts** [comment]
@juliocanares Have you been able to upgrade Engine and resolve your config loading issue?

**Comment by zionts** [comment]
Closing this out. If anyone else runs into this issue, definitely try following the steps above, and if you still are having problems, follow the support path outlined above.

> If the upgrade doesn't resolve your issue, please write back here and I'll be happy to further troubleshoot. Since we don't offer an SLA via Github, you might prefer to reach out to support instead, which you can do via email (support@apollographql.com) or through your Apollo Engine account at https://engine.apollographql.com/support (if you're logged in).

**Comment by clayne11** [comment]
I filed a ticket but I want to confirm I'm having pretty serious issues with this still. I have no way to install the correct version of the binaries. This is my `yarn.lock` file:

```
apollo-engine-binary-darwin@^0.2017.11-137-g908dbec6f:
  version "0.2017.11-84-gb299b9188"
  resolved "https://registry.yarnpkg.com/apollo-engine-binary-darwin/-/apollo-engine-binary-darwin-0.2017.11-84-gb299b9188.tgz#1e863513bb4dce66edd7fe9f12014d55a1c9bed6"

apollo-engine-binary-linux@^0.2017.11-137-g908dbec6f:
  version "0.2017.11-84-gb299b9188"
  resolved "https://registry.yarnpkg.com/apollo-engine-binary-linux/-/apollo-engine-binary-linux-0.2017.11-84-gb299b9188.tgz#02c4e96b1689fd9d1302535d57de8e60bc763688"

apollo-engine-binary-windows@^0.2017.11-137-g908dbec6f:
  version "0.2017.11-84-gb299b9188"
  resolved "https://registry.yarnpkg.com/apollo-engine-binary-windows/-/apollo-engine-binary-windows-0.2017.11-84-gb299b9188.tgz#706bda576e004c0763a95fd1570f7c7a9718a5df"

apollo-engine@^0.6.1:
  version "0.6.1"
  resolved "https://registry.yarnpkg.com/apollo-engine/-/apollo-engine-0.6.1.tgz#5fbc01a7fba89633698911993e5c749cfa7c235f"
  dependencies:
    request "^2.81.0"
    stream-json "^0.5.2"
  optionalDependencies:
    apollo-engine-binary-darwin "^0.2017.11-137-g908dbec6f"
    apollo-engine-binary-linux "^0.2017.11-137-g908dbec6f"
    apollo-engine-binary-windows "^0.2017.11-137-g908dbec6f"
```

**Comment by jeldriks** [comment]
Same here with NPM. `apollo-engine-binary-darwin@^0.2017.11-137-g908dbec6f` is requested, but it resolves to `apollo-engine-binary-darwin@0.2017.11-84-gb299b9188`.

It's my first install of apollo-engine. The only workaround was to `npm i apollo-engine-binary-darwin` in my project's main `package.json` and replace the `apollo-engine/node_modules/apollo-engine-binary-darwin`'s binary with this one.

It's the same with the `-linux` and `-windows`packages.

**Comment by zionts** [comment]
@clayne11, @jeldriks, thanks for bringing this to our attention. We're investigating this issue right now. I'm going to reopen this ticket, and I will update it as it is resolved.

**Comment by blaugold** [comment]
I have the same problem both when using `yarn` and `npm`.  I think its a problem with the semver versioning:

```javascript
const semver = require('semver')

console.log(
    `semver.valid('^0.2017.11-137-g908dbec6f') =>`,
    semver.valid('^0.2017.11-137-g908dbec6f')
)

console.log(
    `semver.satisfies('0.2017.11-137-g908dbec6f', '^0.2017.11-137-g908dbec6f') =>`, 
    semver.satisfies('0.2017.11-137-g908dbec6f', '^0.2017.11-137-g908dbec6f')
)


console.log(
    `semver.satisfies('0.2017.11-84-gb299b9188', '^0.2017.11-137-g908dbec6f') =>`, 
    semver.satisfies('0.2017.11-84-gb299b9188', '^0.2017.11-137-g908dbec6f')
)
```

```
semver.valid('^0.2017.11-137-g908dbec6f') => null
semver.satisfies('0.2017.11-137-g908dbec6f', '^0.2017.11-137-g908dbec6f') => true
semver.satisfies('0.2017.11-84-gb299b9188', '^0.2017.11-137-g908dbec6f') => true
```

According to this little experiment `0.2017.11-84-gb299b9188` satisfies `^0.2017.11-137-g908dbec6f`. The current version format does not seem to be a valid semver version.

**Comment by thepwagner** [comment]
We solved this in https://github.com/apollographql/apollo-engine-js/pull/71 , but haven't released it yet.

To reuse @blaugold 's harness (which is awesome, thanks!)
```
semver.valid('0.2017.11-137-g908dbec6f') => 0.2017.11-137-g908dbec6f
semver.satisfies('0.2017.11-137-g908dbec6f', '0.2017.11-137-g908dbec6f') => true
semver.satisfies('0.2017.11-84-gb299b9188', '0.2017.11-137-g908dbec6f') => false
```

**Comment by sruda** [comment]
I'm experimenting the same issue when I deploy to heroku:

> 32minfo 39m: GraphQL Schema activated
> 
>  32minfo 39m: GraphiQL is now running on http://localhost:43173/graphiql
> 
> level=error msg="Error loading configuration" error="parse config from stdin failed: unknown field \"destination\" in mdg_engine_config_proto.Config_Logging"

**Comment by sruda** [comment]
Quick solution: Disable Apollo Engine until it could be fixed.

**Comment by clayne11** [comment]
When are you planning on releasing this fix?

**Comment by thepwagner** [comment]
@clayne11 fix will be released by 18:00 GMT-4 today

**Comment by zionts** [comment]
Fixed in https://github.com/apollographql/apollo-engine-js/pull/77
