### ISSUE TITLE
Array Arguments Bug

### ISSUE THREAD

**Issue by aaronholla** [apollographql/apollo-engine-js#67]
I have found a bug with Engine that is really frustrating and took me a few hours to figure out was coming from engine.

The problem is that if I run a query with an array as the argument value directly in the query like below. It is returning an array with a single child. It does this with Ints, Booleans, and Floats. For some reason it works fine with Strings.

Please reference these two pads that replicate the issue.
With Engine: [https://launchpad.graphql.com/lk87n3414q](https://launchpad.graphql.com/lk87n3414q)
No Engine: [https://launchpad.graphql.com/0vr0vmlwz5](https://launchpad.graphql.com/0vr0vmlwz5)

Example Query that fails
```
query getAllInts {
  getAllInts(ints: [2, 3, 4])
}

Results:
{
  "data": {
    "getAllInts": [
      234
    ]
  }
}
```
It is really odd because on first request it is sometimes correct as `[ 2, 3, 4 ]`. But then the following requests are incorrect. ( I'm assuming this bug has something to do with the way it caches results )

Work Around
----

As a work around at the moment if you use variables in the query it will work correctly. Like so:

```
query getAllIntsAsVars ($ids: [Int!]) {
  getAllInts(ints: $ids)
}

Query Variables:
{ "ids": [2,3,4] }
```

**Comment by thepwagner** [comment]
This is an issue that was fixed in https://github.com/apollographql/apollo-engine-js/pull/47 . I've created an issue to upgrade the version of `apollo-engine` used by launchpad to fix this bug.

**Comment by aaronholla** [comment]
I downloaded my project and updated to the latest `apollo-engine`. All works no worries. Wish I could just select a version for my server packages on Launchpad.

Thank you! Sorry I didn't see issue #53 when I was searching.
