### ISSUE TITLE
Koa: not handling errors in the correct "koa" way

### ISSUE THREAD

**Issue by zhenyasav** [apollographql/apollo-engine-js#72]
https://github.com/apollographql/apollo-engine-js/blob/master/src/middleware.ts#L60

koa doesn’t like unresolved promises so if we throw exception on that line because `response` is actually null and we try access `statusCode` it makes it unhappy

what we need to do is check if `!!error || !response` and to the correct “koa thing”
we have to make a decision on behaviour too an error like this means that we didn’t get a response from the proxy, so we should probably return a 5xx class error

**Comment by zionts** [comment]
Great catch 👍
