### ISSUE TITLE
Returns "Unknown Content-Type from origin" if other middleware throws an exception

### ISSUE THREAD

**Issue by totorokk** [apollographql/apollo-engine-js#74]
I'm running Apollo Engine as a separate process on the KOA/GraphQL server, and `engine.koaMiddleware` is used as the 1st middleware. Now if any other middleware (before it hits the /graphql endpoint) throws an exception, the Apollo Engine return the error below. 
```
{
    "errors": [
        {
            "message": "Unknown Content-Type from origin"
        }
    ]
}
```

Is it by design, or could the error handling be more transparent to non-GraphQL errors?

**Comment by zionts** [comment]
Thanks for reaching out on this. We can definitely be more descriptive with that error. To help you troubleshoot, which version of the engine proxy binary are you using? You can check this via the command `node_modules/apollo-engine-binary-darwin/engineproxy_darwin_amd64 -version`. The "Unknown Content-Type from origin"  error should only be thrown if Engine Proxy receives a response from an origin that isn't specified as JSON or CBOR. What content-type is your GraphQL origin returning? Is it setting the content-type to be, for example, application/json?

**Comment by totorokk** [comment]
@zionts Thanks for the explanation! I was using ctx.throw, which sets the content-type to text/plain. After setting the response to json, it works fine now.

**Comment by fc** [comment]
A note for others: you may also get this error if your `graphqlPort` is incorrect.
