### ISSUE TITLE
Errors with last two versions

### ISSUE THREAD

**Issue by shauravg** [apollographql/apollo-engine-js#81]
**Problem with version 0.8.0:**
- Cannot find module 'apollo-engine'

**Problem with version 0.6.1:**
Engine crashed unexpectedly with code: 1
time="2017-12-19T17:35:44-08:00" level=error msg="Error loading configuration" error="parse config from stdin failed: unknown field \"destination\" in mdg_engine_config_proto.Config_Logging"

**server.js code:**
import { Engine } from 'apollo-engine';
const app = express();
const port = config.get('PORT');

const engine = new Engine({
	engineConfig: {
		apiKey: <API_KEY>,
		logging: {
			level: 'DEBUG'
		}
	},
	graphqlPort: port,
	endpoint: '/graphql',
	dumpTraffic: true
});
engine.start();
app.use(engine.expressMiddleware());

app.use('/graphql', bodyParser.json(), graphqlExpress({
	schema,
	context: {},
	tracing: true,
	cacheControl: true
}));

app.use('/graphiql', graphiqlExpress({
	endpointURL: '/graphql'
}));

app.use(require('compression'));

const graphQLServer = createServer(app);

**Comment by jamesone** [comment]
I also get `Cannot find module 'apollo-engine'` with 0.8.0

**Comment by sbr464** [comment]
same issue, was just doing research and found this issue. Working fine before upgrade to 0.8.0

using node 8.9.3, tried with 8.9.1 also

<img width="712" alt="screen shot 2017-12-19 at 11 28 08 pm" src="https://user-images.githubusercontent.com/8600215/34194141-7882cda4-e514-11e7-86e8-0c50031c179d.png">

**Comment by thepwagner** [comment]
Hey everyone - there was an issue with the `0.8.0` release, it is fixed in the `0.8.1` release.

Sorry about that.

**Comment by shauravg** [comment]
Thank you for the fast response @thepwagner. With 0.8.1, I get neither of these errors and is successfully uploading to the engine service.
