### ISSUE TITLE
Apollo Engine interferes with HMAC authetication

### ISSUE THREAD

**Issue by gajus** [apollographql/apollo-engine-js#83]
My service is using HMAC authentication as illustrated in this code example, https://gist.github.com/gajus/a50295dfd59b5f11cb6d816d2a9cf0cb.

The backend service receives request headers looking something like:

```json
{
  "accept-encoding": "gzip",
  "authorization": "APPLAUDIENCE {\"accessKey\":\"8309114474260837\",\"nonce\":\"0.7853585630400997\",\"signature\":\"1ee3fd5e012af24f94d6c20b7415e6563763b24f0a607a416291f7aa8dd71b89\",\"signedHeaders\":[\"host\"],\"timestamp\":1513761778}",
  "connection": "close",
  "content-length": "70",
  "content-type": "application/json",
  "host": "127.0.0.1:7000",
  "user-agent": "Go-http-client/1.1",
  "x-engine-from": "1807e0816c0c74980950194ef14ed4eb7fc28380cbdfb802cfc60d4bfd88b9045c78427eb309900417a24c921baeedbb"
}

```

The problem here is the `host` header.

The HMAC signature includes `host` header into the hash. `127.0.0.1:7000` is the address of the backend as configured via Apollo Engine configuration `endpoint` and `graphqlPort`. The actual API is reachable via another host (https://go2cinema.com/api/), i.e. the API client is using `go2cinema.com` as a host.

A solution is to have a configuration that would make `apollo-engine` use the original host header value.

**Comment by gajus** [comment]
> Hi @gajus thanks for bringing this to our attention! I'm working on this right now, and I'll update here when this is resolved.

There could be a case made that apollo-engine proxy is behaving like expected. A possible workaround would be to create yet another HTTP service above apolle-engine that handles only HMAC authentication. This would create a proxy chain `[HMAC auth] -> [apollo-engine proxy] -> [GraphQL service]`.

**Comment by gajus** [comment]
> There could be a case made that apollo-engine proxy is behaving like expected. A possible workaround would be to create yet another HTTP service above apolle-engine that handles only HMAC authentication. This would create a proxy chain [HMAC auth] -> [apollo-engine proxy] -> [GraphQL service].

This approach adds a really big overhead. The response time increased from 200ms to ±2000ms. I am using `http-proxy-middleware`.

@zionts Are you still working on a fix?

**Comment by zionts** [comment]
Hey @gajus yep, I am. Are you only seeing this behavior for non-GraphQL queries or is Engine not forwarding Host header for GraphQL queries as well?

**Comment by gajus** [comment]
The latter.

**Comment by yoDon** [comment]
@zionts is there any example or hints you can offer on how to apply HMAC signing to a GraphQL query (from apollo client to apollo server)?
