### ISSUE TITLE
is this compatible with Hapi 17?

### ISSUE THREAD

**Issue by kdong007** [apollographql/apollo-engine-js#85]
this is what I got 

```
Debug: internal, implementation, error 
    TypeError: reply.continue is not a function
    at server.ext (/Users/kdong/api_server/node_modules/apollo-engine/src/middleware.ts:81:84)
    at module.exports.internals.Manager.execute (/Users/kdong/api_server/node_modules/hapi/lib/toolkit.js:35:106)
    at module.exports.internals.Request._invoke (/Users/kdong/api_server/node_modules/hapi/lib/request.js:299:55)
    at <anonymous>
{
  "error": "reply.continue is not a function",
  "timestamp": 1513963285693,
  "level": "warn",
  "environment": "dev"
}
```

the rely object has a property of {continue: symbol(continue)}

**Comment by zionts** [comment]
Hi @kdong007 
Right now, engine proxy does not support Hapi 17. If support for Hapi 17 is important for you, then we would welcome a pull request! I've started off some of the work on a [branch](https://github.com/apollographql/apollo-engine-js/tree/adam/upgradehapi) to give a head start. Feel free to reach out if you have any questions on this.

All the best,
Adam

**Comment by phenomax** [comment]
When Hapi 17?

**Comment by thepwagner** [comment]
Xref breadcrumb https://github.com/apollographql/apollo-server/pull/687

**Comment by glasser** [comment]
1.0 will support hapi v17 (and is tested with it). I think it will still support v16 too, but honestly it's very difficult to understand the docs around hapi (not all of which have been updated for v17) and it's challenging to make a single test suite test both APIs. If we broke v16, we'd be happy to take bug reports and try to fix it.  See #150.
