### ISSUE TITLE
frontend proxy settings injection doesnt work

### ISSUE THREAD

**Issue by Zapnick** [apollographql/apollo-engine-js#86]
Hi guys,
my node version 9.3. I use restify. I cant inject a proxy port by:

const engine = new Engine({
  engineConfig: {
    apiKey: 'blablabla',
  },
  frontend:
    {
      host: '127.0.0.1',
      port: 8008,
      endpoint: '/graphql',
    },
  graphqlPort: PORT,
});

In apollo-engine/src/index.ts line 211:

 // Inject frontend, that we will route
        const frontend = Object.assign({}, this.frontendParams, {
            host: '127.0.0.1',
            endpoint,
            port: 0,
        });

always leads to an override of my arguments in "this.fronendParams". Frontend is always:

{
            host: '127.0.0.1',
            endpoint,
            port: 0,
        }

May u help me please with this?
thanks

**Comment by zionts** [comment]
Hi @Zapnick,
I see why this might be confusing, but the `frontend` argument is actually different from the `frontends` field in the Apollo Engine configuration. If you want to set up a custom configuration for Engine, you should actually specify the `config` argument, something like
```
config: {
    origins: [{...}]
    frontends: [{...}]
}
```
The `frontend` argument is for injecting custom settings for all frontends, such as extensions to be stripped or blacklisted. When using the sidecar in its standard way, it performs a double proxy from/to your Node app and sets up the frontend and origin automatically, so you shouldn't need to specify a custom frontend unless you are configuring it differently or have multiple frontends / origins.

If you look into the `start()` method that you referenced on lines [217-221](https://github.com/apollographql/apollo-engine-js/blob/master/src/index.ts#L217), you'll see that it's actually concerned about the `childconfig` object which it's using the spawn the actual Engine process in `spawnChild()`.

If this clears things up for you, let me know, and if not then I'm here or you can submit a ticket to support or reach out via Slack :)
