### ISSUE TITLE
Tests for `privateVariables`

### ISSUE THREAD

**Issue by mattfysh** [apollographql/apollo-engine-js#89]
Hey there, love the work on this tool :)

We have some sensitive variables being used and I've tracked down and implemented `privateVariables` to prevent them from leaking. However, I've noticed there doesn't appear to be any test coverage in this repo for that feature... is that because it's a simple passthrough into the underlying bin? Just wanted to check if there are test cases somewhere for this feature, given the security implications if this feature were to regress. Thanks!!

**Comment by thepwagner** [comment]
That's correct - the `privateVariables` configuration is passed through to the underlying binary, and filtering is verified in unit tests vs that binary's code.

Also worth noting - the binary rejects unknown config fields (i.e. if you setup `privateVariables` and it ends up renamed/removed/regressed in later builds, the config will be rejected at startup).

**Comment by mattfysh** [comment]
Awesome, thank you @thepwagner
