### ISSUE TITLE
Engine with whitelisted persisted queries

### ISSUE THREAD

**Issue by aaronCammy** [apollographql/apollo-engine-js#90]
We are currently implementing whitelisted persisted queries which are preapproved queries identified by an id. For that to happen we need to translate an id submitted by users to the graphql queries to be used by the rest of the request. 

In Engines express middleware it currently only accepts a raw express request(unparsed body) which causes problems since we have cannot revert a request to its unparsed state. Anyway for engine middleware to accept a body-parser parsed request?

**Comment by zionts** [comment]
Hi @aaronCammy 
If this feature is important to you, then we would welcome a PR that allows the express middleware to accept a parsed request with a certain flag, for instance. Additionally, I'd like to point out that Apollo Engine now has [support for automatic persisted queries](https://www.apollographql.com/docs/engine/auto-persisted-queries.html) if that's something you think could help solve your problem without needing to maintain your own implementation. Feel free to reach out if you have any questions!

All the best,
Adam
