### ISSUE TITLE
TypeError: Cannot read property 'middlewareParams' of undefined

### ISSUE THREAD

**Issue by ChiShouWu** [apollographql/apollo-engine-js#91]
I add apollo engine into my project as this [tutorial](https://dev-blog.apollodata.com/tutorial-building-a-graphql-server-cddaa023c035)
But as I request to my API
```TypeError: Cannot read property 'middlewareParams' of undefined```
This problem shown, how can I fix it?

**Comment by ChiShouWu** [comment]
`const express = require('express');
const bodyParser = require('body-parser');
const { graphqlExpress, graphiqlExpress } = require('apollo-server-express');
const compression = require('compression');
const { Engine } = require('apollo-engine');

const app = express();
const engine = new Engine({
  engineConfig: {
    apiKey: /* API key*/,
  },
  graphqlPort: process.env.PORT || 3000,
  dumpTraffic: true,
  startupTimeout: 5000,
});

engine.start();
app.use(engine.expressMiddleware); // must be first middleware

const buildOptions = async (req, res) => {
  return {
    schema,
    tracing: true,
    cacheControl: true,
  };
};
app.use(
  '/graphql',
  graphqlExpress(buildOptions),
  bodyParser.urlencoded({ extended: false }),
  bodyParser.json(),
);
app.use('/graphiql', graphiqlExpress({ endpointURL: '/graphql' }));
app.listen(3000, () =>
console.log(
  `GraphiQL is now running on http://localhost:3000/graphiql`
  )
);
module.exports = app;
`

**Comment by thepwagner** [comment]
```app.use(engine.expressMiddleware); // must be first middleware```

I think this should be:
```app.use(engine.expressMiddleware()); // must be first middleware```
