### ISSUE TITLE
question about engine proxy

### ISSUE THREAD

**Issue by lfender6445** [apollographql/apollo-engine-js#94]
I am curious, what are some of the advantages and disadvantages / design motivations of running apollo engine as a proxy?

**Comment by zionts** [comment]
Hi Luke,
There are a number of reasons that we have chosen the architecture we have, most of which are concerned with speed – both speed for your application and speed of development. It's worthwhile to point out that Engine Proxy is a thin, fast proxy that forwards tracing information, among other things, to the Engine cloud service. If you want to have a more detailed conversation about this, I'm happy to chime in, but this isn't the right place for this conversation. Check out the #Engine channel of the [Apollo Slack](https://www.apollographql.com/#slack).
